### ISSUE TITLE
main_split_image

### ISSUE THREAD

**Issue by zjw102** [deeptibhegde/CLIP-goes-3D#6]
Hi,I have downloaded ScanObjectNN, but "main_split_image "is not in it. How do I get it

**Comment by deeptibhegde** [comment]
"main_split_image" is not required for zero-shot inference and fine-tuning. ``` ScanObjectNNDataset.py ``` has been updated to reflect that. You should be able to run all commands with the main_split data.

**Comment by zjw102** [comment]
Thank you for your help，The complete error information is below：
Traceback (most recent call last):
  File "/home/zjw/PycharmProjects/CLIP-goes-3D-main/utils/registry.py", line 285, in build_from_cfg
    return obj_cls(cfg)
  File "/home/zjw/PycharmProjects/CLIP-goes-3D-main/datasets/ScanObjectNNDataset.py", line 236, in __init__
    self.images = np.array(h5['images']).astype(np.float32)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zjw/anaconda3/envs/cg3d/lib/python3.9/site-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'images' doesn't exist)"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjw/PycharmProjects/CLIP-goes-3D-main/eval.py", line 608, in <module>
    main()
  File "/home/zjw/PycharmProjects/CLIP-goes-3D-main/eval.py", line 123, in main
    builder.dataset_builder(args, config.dataset.scan) 
  File "/home/zjw/PycharmProjects/CLIP-goes-3D-main/tools/builder.py", line 77, in dataset_builder
    dataset = build_dataset_from_cfg(config._base_, config.others)
  File "/home/zjw/PycharmProjects/CLIP-goes-3D-main/datasets/build.py", line 15, in build_dataset_from_cfg
    return DATASETS.build(cfg, default_args = default_args)
  File "/home/zjw/PycharmProjects/CLIP-goes-3D-main/utils/registry.py", line 147, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/zjw/PycharmProjects/CLIP-goes-3D-main/utils/registry.py", line 288, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: 'ScanObjectNN_hardest: "Unable to open object (object \'images\' doesn\'t exist)"'

It is precisely because it is the latest repository that there is no "image". 
In addition, what I would like to ask you is what these two instructions should be filled in
--exp_name {NAME FOR EXPT}  --ckpts {CKPT PATH}
Can you send an example?Thank you.

**Comment by deeptibhegde** [comment]
Please pull the latest version of the repository, the error you report would have only appeared in a previous version. You can put any meaningful name in the --exp_name command (e.g. point_mlp_pretrain). During inference, it helps to put the same name as the model you are evaluating. In the --ckpts command, enter the path to the ckpt you wish to evaluate or load for initialization.
